# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/forky.yaml.j2

forky:
  fullnameOverride: forky
  replicas: 1
  image:
    repository: ethpandaops/forky
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 256m
      memory: 512Mi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: forky.peerdas-devnet-0.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix
  config:
    listen_addr: ":5555"
    pprof_addr: ":6060"
    log_level: "debug"
    metrics:
      addr: ":9090"
      enabled: true
    forky:
      retention_period: "1m"
      store:
        type: memory
      indexer:
        dsn: "file::memory:?cache=shared"
        driver_name: sqlite
      ethereum:
        network:
          name: "peerdas-devnet-0"
          spec:
            seconds_per_slot: 12
            slots_per_epoch: 32
            genesis_time: 1715890114
      sources:
        - name: bootnode-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.bootnode-1.peerdas-devnet-0.ethpandaops.io
            polling_interval: "12s"
        - name: grandine-geth-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.grandine-geth-1.peerdas-devnet-0.ethpandaops.io
            polling_interval: "12s"
        - name: lighthouse-geth-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.lighthouse-geth-1.peerdas-devnet-0.ethpandaops.io
            polling_interval: "12s"
        - name: lighthouse-nethermind-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.lighthouse-nethermind-1.peerdas-devnet-0.ethpandaops.io
            polling_interval: "12s"
        - name: nimbus-geth-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.nimbus-geth-1.peerdas-devnet-0.ethpandaops.io
            polling_interval: "12s"
        - name: prysm-geth-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.prysm-geth-1.peerdas-devnet-0.ethpandaops.io
            polling_interval: "12s"
        - name: prysm-nethermind-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.prysm-nethermind-1.peerdas-devnet-0.ethpandaops.io
            polling_interval: "12s"
        - name: teku-geth-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.teku-geth-1.peerdas-devnet-0.ethpandaops.io
            polling_interval: "12s"
        - name: teku-nethermind-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.teku-nethermind-1.peerdas-devnet-0.ethpandaops.io
            polling_interval: "12s"
