# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/testnet-homepage.yaml.j2

testnet-homepage:
  fullnameOverride: homepage

  replicas: 1

  image:
    repository: ethpandaops/ethereum-testnet-homepage
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 33m
      memory: 64Mi
  ingress:
    enabled: true

    className: ingress-nginx-public

    hosts:
      - host: peerdas-devnet-0.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  customMarkdown: |-
    ## Network Spec
    https://notes.ethereum.org/@ethpandaops/peerdas-devnet-0

    ## Ansible setup
    https://github.com/ethpandaops/peerdas-devnets

    ## Client versions
    https://github.com/ethpandaops/peerdas-devnets/blob/master/ansible/inventories/devnet-0/group_vars/all/images.yaml

    ## Validator ranges
    - https://config.peerdas-devnet-0.ethpandaops.io/api/v1/nodes/validator-ranges

    Some examples:
    ```sh
    ## Pretty print in YAML format
    curl -s https://config.peerdas-devnet-0.ethpandaops.io/api/v1/nodes/validator-ranges \
      | yq '.ranges' -P
    ```

    ## Ethereum node inventory
    - https://config.peerdas-devnet-0.ethpandaops.io/api/v1/nodes/inventory

    Some examples on how to filter specific data from the node inventory:
    ```sh
    # Getting execution layer client enodes
    curl -s https://config.peerdas-devnet-0.ethpandaops.io/api/v1/nodes/inventory \
      | jq -r '.ethereum_pairs[] | .execution.enode'
    # Getting conseus layer client ENRs
    curl -s https://config.peerdas-devnet-0.ethpandaops.io/api/v1/nodes/inventory \
      | jq -r '.ethereum_pairs[] | .consensus.enr'
    ```

    ## Genesis configuration
    ### Execution layer clients
    - https://config.peerdas-devnet-0.ethpandaops.io/el/genesis.json
    - https://config.peerdas-devnet-0.ethpandaops.io/el/chainspec.json

    ### Consensus layer clients
    - https://config.peerdas-devnet-0.ethpandaops.io/cl/config.yaml
    - https://config.peerdas-devnet-0.ethpandaops.io/cl/genesis.ssz
    - https://config.peerdas-devnet-0.ethpandaops.io/cl/deploy_block.txt
    - https://config.peerdas-devnet-0.ethpandaops.io/cl/deposit_contract.txt
    - https://config.peerdas-devnet-0.ethpandaops.io/cl/deposit_contract_block.txt


  customArgs:
    - -b
    - https://peerdas-devnet-0.ethpandaops.io

  config:
    baseURL: https://peerdas-devnet-0.ethpandaops.io
    languageCode: en-us
    title: peerdas-devnet-0
    theme: PaperMod
    markup:
      highlight:
        codeFences: true
        guessSyntax: true
        lineNos: false
        style: monokai
    params:
      disableThemeToggle: true
      defaultTheme: dark
      ethereum:
        faucetUrl: https://faucet.peerdas-devnet-0.ethpandaops.io
        rpcUrl: https://rpc.peerdas-devnet-0.ethpandaops.io
        beaconRpcUrl: https://beacon.peerdas-devnet-0.ethpandaops.io
        explorerUrl: https://explorer.peerdas-devnet-0.ethpandaops.io
        forkmonUrl: https://forkmon.peerdas-devnet-0.ethpandaops.io
        beaconexplorerUrl: "https://peerdas-devnet-0.beaconcha.in"
        doraUrl: https://dora.peerdas-devnet-0.ethpandaops.io
        checkpointSyncUrl: "https://checkpoint-sync.peerdas-devnet-0.ethpandaops.io"
        blobscanUrl: https://blobscan.com
        blobscanethpandaUrl: https://blobscan.peerdas-devnet-0.ethpandaops.io
        ethstatsUrl: https://ethstats.peerdas-devnet-0.ethpandaops.io
        chainName: "peerdas-devnet-0"
        chainId: "7071720988"
        github: https://github.com/ethpandaops/peerdas-devnets/tree/master/network-configs/devnet-0
      metamask:
        enabled: true
      logo:
        enabled: false
        url: https://i.imgur.com/M0gEdpw.png
      assets:
        favicon: https://i.imgur.com/M0gEdpw.png
        favicon16x16: https://i.imgur.com/M0gEdpw.png
        favicon32x32: https://i.imgur.com/M0gEdpw.png
        apple_touch_icon: https://i.imgur.com/M0gEdpw.png
        safari_pinned_tab: https://i.imgur.com/M0gEdpw.png

      links:
      - name: "Devnet Spec"
        dataLookup: github
      - name: "JSON RPC"
        dataLookup: rpcUrl
      - name: "Beacon RPC"
        dataLookup: beaconRpcUrl
      - name: "Explorer"
        dataLookup: explorerUrl
      - name: "Dora the Explorer"
        dataLookup: doraUrl
      - name: "Beaconchain explorer"
        dataLookup: "beaconexplorerUrl"
      - name: "Blobscan"
        dataLookup: blobscanUrl
      - name: "Blobscan ethpanda edition"
        dataLookup: blobscanethpandaUrl
      - name: "Checkpoint Sync"
        dataLookup: checkpointSyncUrl
      - name: "Faucet"
        dataLookup: faucetUrl
      - name: "Forkmon"
        dataLookup: forkmonUrl
      - name: "Ethstats"
        dataLookup: ethstatsUrl
    menu:
      main:
        - identifier: ethereum-website
          name: ethereum.org
          url: https://ethereum.org
          weight: 30
    disableKinds: ["taxonomy", "taxonomyTerm"]
    copyright: "Long live the surge"
